repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  kubeContext: asus

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false
  installed: true
